#Project Euler Problem 436 - Unfair Wager 

import numpy as np

import time

tic = time.time()

def simulation():
    #Louisse's turn
    S, r_l = 0, 0
    while S < 1:
        r_l = np.random.rand()
        S += r_l #r_l is the last random number added to S, generated by Louise

    #Julie's turn
    r_j = 0 
    while S < 2:
        r_j = np.random.rand()
        S += r_j #r_2 is the last random number added to S, generated by Julie
    
    return r_j > r_l

def monte_carlo(num_simulations):
    julie_wins = 0

    for _ in range(num_simulations):
        if simulation():
            julie_wins += 1
            
    return julie_wins / num_simulations 

iterations = 10**9

prob = monte_carlo(iterations)

print("Estimated probability that the second player wins: %.10f" % prob)

tac = time.time()

print("Elapsed time: %.2f seconds" % (tac - tic))